name: Build README

on:
  push:
    branches:    
      - 'main'
  schedule:
  - cron: "30 15 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v2
      uses: actions/setup-ruby@v1
      with:
        bundler-cache: true 
    - name: Update stars and last updated
      run:  bundle exec updateReadme.md
    - name: Commit and push
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "Github Actions Cronjob"
        git add -A
        git commit -m --allow-empty "Update Stars and Last Updated"
        git push